import { Category, Product, Order, DashboardStats } from './types';

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Electronic devices and gadgets',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Clothing',
    slug: 'clothing',
    description: 'Fashion and apparel',
    createdAt: '2024-01-16T10:00:00Z',
  },
  {
    id: '3',
    name: 'Home & Garden',
    slug: 'home-garden',
    description: 'Home improvement and garden supplies',
    createdAt: '2024-01-17T10:00:00Z',
  },
  {
    id: '4',
    name: 'Sports',
    slug: 'sports',
    description: 'Sports equipment and fitness gear',
    createdAt: '2024-01-18T10:00:00Z',
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Wireless Headphones',
    description: 'Premium noise-cancelling wireless headphones',
    price: 299.99,
    categoryId: '1',
    categoryName: 'Electronics',
    stock: 45,
    unit: 'piece',
    moq: 1,
    featured: true,
    images: ['https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg'],
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Smart Watch',
    description: 'Fitness tracker with heart rate monitor',
    price: 199.99,
    categoryId: '1',
    categoryName: 'Electronics',
    stock: 32,
    unit: 'piece',
    moq: 1,
    featured: true,
    images: ['https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg'],
    createdAt: '2024-02-02T10:00:00Z',
  },
  {
    id: '3',
    name: 'Cotton T-Shirt',
    description: 'Comfortable 100% cotton t-shirt',
    price: 29.99,
    categoryId: '2',
    categoryName: 'Clothing',
    stock: 120,
    unit: 'piece',
    moq: 1,
    featured: false,
    images: ['https://images.pexels.com/photos/1192335/pexels-photo-1192335.jpeg'],
    createdAt: '2024-02-03T10:00:00Z',
  },
  {
    id: '4',
    name: 'Running Shoes',
    description: 'Lightweight running shoes with cushioning',
    price: 89.99,
    categoryId: '4',
    categoryName: 'Sports',
    stock: 65,
    unit: 'piece',
    moq: 1,
    featured: true,
    images: ['https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg'],
    createdAt: '2024-02-04T10:00:00Z',
  },
  {
    id: '5',
    name: 'Garden Tools Set',
    description: 'Complete set of essential garden tools',
    price: 49.99,
    categoryId: '3',
    categoryName: 'Home & Garden',
    stock: 28,
    unit: 'piece',
    moq: 1,
    featured: false,
    images: ['https://images.pexels.com/photos/4505447/pexels-photo-4505447.jpeg'],
    createdAt: '2024-02-05T10:00:00Z',
  },
];

export const mockOrders: Order[] = [
  {
    id: '1',
    orderNumber: 'ORD-001',
    customerName: 'John Doe',
    customerEmail: 'john@example.com',
    total: 329.98,
    status: 'completed',
    items: [
      { id: '1', productId: '1', productName: 'Wireless Headphones', quantity: 1, price: 299.99 },
      { id: '2', productId: '3', productName: 'Cotton T-Shirt', quantity: 1, price: 29.99 },
    ],
    createdAt: '2024-03-01T10:00:00Z',
  },
  {
    id: '2',
    orderNumber: 'ORD-002',
    customerName: 'Jane Smith',
    customerEmail: 'jane@example.com',
    total: 199.99,
    status: 'processing',
    items: [
      { id: '3', productId: '2', productName: 'Smart Watch', quantity: 1, price: 199.99 },
    ],
    createdAt: '2024-03-02T10:00:00Z',
  },
  {
    id: '3',
    orderNumber: 'ORD-003',
    customerName: 'Bob Johnson',
    customerEmail: 'bob@example.com',
    total: 139.98,
    status: 'pending',
    items: [
      { id: '4', productId: '5', productName: 'Garden Tools Set', quantity: 1, price: 49.99 },
      { id: '5', productId: '4', productName: 'Running Shoes', quantity: 1, price: 89.99 },
    ],
    createdAt: '2024-03-03T10:00:00Z',
  },
  {
    id: '4',
    orderNumber: 'ORD-004',
    customerName: 'Alice Williams',
    customerEmail: 'alice@example.com',
    total: 89.99,
    status: 'completed',
    items: [
      { id: '6', productId: '4', productName: 'Running Shoes', quantity: 1, price: 89.99 },
    ],
    createdAt: '2024-03-04T10:00:00Z',
  },
  {
    id: '5',
    orderNumber: 'ORD-005',
    customerName: 'Charlie Brown',
    customerEmail: 'charlie@example.com',
    total: 299.99,
    status: 'cancelled',
    items: [
      { id: '7', productId: '1', productName: 'Wireless Headphones', quantity: 1, price: 299.99 },
    ],
    createdAt: '2024-03-05T10:00:00Z',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalOrders: 5,
  pendingOrders: 1,
  totalRevenue: 1059.93,
  totalProducts: 5,
};
